# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: xrates.proto for package 'xrates'

require 'grpc'
require 'xrates'

module Xrates
  module XRates

    # TODO: add proto service documentation here
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'xrates.XRates'

      rpc :Get, Currency, Rate
      rpc :All, Currencies, Rates
    end

    Stub = Service.rpc_stub_class
  end
end
