# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xrates.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "xrates.Currency" do
    optional :currency, :string, 1
  end
  add_message "xrates.Rate" do
    optional :rate, :double, 1
  end
  add_message "xrates.Currencies" do
    repeated :currencies, :string, 1
  end
  add_message "xrates.Rates" do
    map :rates, :string, :double, 1
  end
end

module Xrates
  Currency = Google::Protobuf::DescriptorPool.generated_pool.lookup("xrates.Currency").msgclass
  Rate = Google::Protobuf::DescriptorPool.generated_pool.lookup("xrates.Rate").msgclass
  Currencies = Google::Protobuf::DescriptorPool.generated_pool.lookup("xrates.Currencies").msgclass
  Rates = Google::Protobuf::DescriptorPool.generated_pool.lookup("xrates.Rates").msgclass
end
